### ISSUE TITLE
LandBuilding01 (Corner Building) can be shot through

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#18]
LandBuilding01 (Corner Building) can be shot through at the edges of the building.

**Comment by Scorch052** [comment]
It seems like only some parts can be shot through. I'm not certain what the cause is.

**Comment by Lumnuon** [comment]
"most of the fire through building issues are from the fire geometry not being mapped properly, ie, multiple objects mapped to one ComponentXX" - Theebu
