### ISSUE TITLE
The LMG and SMG are not appearing in the virtual arsenal

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#26]

**Comment by Scorch052** [comment]
I cannot, for the life of me, figure out the fucking cause of this. If someone else wants to lend a pair of fresh eyes, it may help.

**Comment by theebu** [comment]
I'll take a look at it, should be an easy fix

**Comment by Scorch052** [comment]
issue was related to baseWeapon config entry.
