### ISSUE TITLE
The majority of the weapon sounds seem to have decreased in quality

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#36]

**Comment by Lumnuon** [comment]
Maybe we should use vanilla sounds until we have resolved the issue? I also believe that our current sounds are missing tails that were introduced in the last few arma updates.

**Comment by Lumnuon** [comment]
Proposal:

AK-12 -> MA5A / MA5B
M320 LRR -> SRS99D
GM6 Lynx -> SRS99C
Sting 9mm / PDW2000 -> M7/Caseless SMG
Navid 9.3mm -> M73 LMG
Katiba -> MA5K

**Comment by Scorch052** [comment]
I cannot replicate this. Weapons sound exactly the same.

**Comment by Lumnuon** [comment]
Hm, I only compiled OPTRE_weapons. Are necessary files in other pbos aswell? For me the sounds are very quiet and sound very strange.

**Comment by Lumnuon** [comment]
https://youtu.be/wtzWk2Vd6UQ
