### ISSUE TITLE
"Tick" sounds after shooting the M7 in full-auto

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#38]

**Comment by Scorch052** [comment]
Once again, cannot replicate this. Maybe record it?

**Comment by Lumnuon** [comment]
https://youtu.be/wtzWk2Vd6UQ

**Comment by Scorch052** [comment]
Yeah thats definitely some kind of issue on your end as mine sound nothing like that. Can anyone else confirm this issue?
