### ISSUE TITLE
UH-144 Falcon "Innie" camo selection option needs to be removed

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#40]
The "Innie" camo selection option (in the VA) for the Falcon should be removed since there is no Innie Falcon.

**Comment by Scorch052** [comment]
The is no Innie falcon so I'm not sure what this is referring to.

**Comment by Lumnuon** [comment]
already discussed this with theebu, there shouldn´t be a innie camo selection available in the first place - forgot to change the title of the ticket
