### ISSUE TITLE
Elephant HRV crashes the game

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#56]
It seems like occupying the driver´s position crashes the game after a few seconds.

The crash seems to be a memory crash, somewhat related to x64.

**Comment by Whitefame** [comment]
-Added proxies and ffv positions
-Added ViV positions
-Configed wheels/suspensions and animations
-Improved all lods but still havn't added the hitpoints lod so in ace it can't be destroyed.
My don't crash anymore but it should be nice if someone else could also confirm it.
