### ISSUE TITLE
SOEIV Drop Pod crashes the game

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#59]
The Drop Pod is supposedly crashing the game for some when not landing straight on the ground (hitting buildings, etc.).

**Comment by Scorch052** [comment]
This is has been fixed apparently by White. Waiting for him to push it.

**Comment by Lumnuon** [comment]
@Whitefame can this issue be closed?

**Comment by Whitefame** [comment]
Yes, it works fine for me.
