### ISSUE TITLE
Apex VTOL flight model for the Pelican

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#60]
This has been brought up a while ago and I am only opening this issue because a decent amount of people seem to want it. Open for discussion and certainly not a definitive plan yet. @Scorch052 I believe you were critical of it before? It improved somewhat now with being able to control the thrust angle manually.

**Comment by Scorch052** [comment]
This is one of those vocal minority things. Having tested all of the VTOL aircraft extensively, I've come to the conclusion that they cannot emulate VTOL well enough and reliably enough to make a switch viable.
