### ISSUE TITLE
Make the integrated compass of the MA5 series work

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#70]

**Comment by Lumnuon** [comment]
Animation event handler not suitable for updating the compass:
![unknown](https://user-images.githubusercontent.com/8450196/30063225-448978a4-924e-11e7-95ca-a2210272c59d.png)

-credits: BigWilk

**Comment by Scorch052** [comment]
This is an engine constraint we won't be able to overcome until BIS addresses animationsources for weapons
