### ISSUE TITLE
UNSC body armor is insufficient for standard OPTRE calibres

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#80]
"So in the test, I tested out the OPTRE Army armor both in and out of ACE with Human players, not AI. For AI can take 1 - 3 shots more then a Human Player. Making armor value test worthless on player survival.

The results are
1 round from from 7.62
2 rounds from 6.5
4 rounds from 5.56

From these Numbers, I lined up my guys at 200 meters and Shot them in the Chest.

Next I had them Equip different Vanilla NATO armor and repeated the test. Afterwards is decided to test out the ODST uniforms.

In the end, these were the results.

ODST armor = Nato Special Carrier Rig, Which can take 2 7.62 Rounds
ARMY armor = Nato Carrier Rig.

The problem is that Nato Vanilla Armor is not realistic in where they are designed to take 2-3 7.62mm rounds on the plate.

Instead they were balanced around 5.56mm and 6.5mm rounds for in the Base game, that is what the Majority of Opfor and Green for are equipped with.

With Halo Universe with 7.62 as standard issue over 5.56, these values ends up making the UNSC Uniforms nothing more then running around nakid.

Now I didn't test the Fatigues out to see where their values were at, but I'll probably do that at a later date" - Theron

**Comment by Lumnuon** [comment]
Increasing Body armor should be done with caution to not implement bullet sponges.

**Comment by Scorch052** [comment]
I'm going to do a complete overhaul of the damage models and damage of weapons systems in the next update.

**Comment by BWCSM** [comment]
Yeah I'd say it needs looking at. Played a few games, vs lots of ai, or in CQB it can become annoying.
