### ISSUE TITLE
Zeus Game Master Moudle Default Addon Option no longer brings all OPTRE assets into ZEUS

### ISSUE THREAD

**Issue by BWCSM** [Scorch052/OPTRE_DEV#83]
Useing these settings used to bring all optre assets into game. It does not anymore. 

![image](https://user-images.githubusercontent.com/14022423/31352363-70033f40-ad26-11e7-9949-a638c34e7aa6.png)

**Comment by BWCSM** [comment]
On more investigation, the "Manage Addons" Module does not work now either. What I was seeing that made me think it was, is in the empty catagory some OPTRE Vehicle still show up in Zeus.

**Comment by BWCSM** [comment]
More detail by default only the rocket pod seems to be showing: https://media.discordapp.net/attachments/342416459261280256/367005575977893890/missing.PNG?width=160&height=566

**Comment by Scorch052** [comment]
Related to how I packed the mods. Will fix this and the HEVs and push a hotfix.
