### ISSUE TITLE
SRS99C ammo has no ballistic curve

### ISSUE THREAD

**Issue by Lumnuon** [Scorch052/OPTRE_DEV#99]
I believe we had discussed this before because ?they are not supposed to have a ballistic curve?. After @BWCSM and I joined a community Operation and were asked about the strange behavior of the Sniper rifles. We tested them out themselves, which is the reason this is brought up ?again?.

**Comment by Scorch052** [comment]
Bullets are meant to fly straight with no curve or drop. Intended Behavior

**Comment by Lumnuon** [comment]
We discussed this a while ago and even you agreed that we should give them a ballistic curve for the sake of gameplay. Long distance shooting is incredibly boring otherwise and anyone can do it.
